### GET all users
GET localhost:5000/users

### GET all services
GET localhost:5000/services

### search services
GET localhost:5000/services
Content-Type: application/json

{
  "search_text": "cheese",
  "sort": {
      "by": "price",
      "reverse": true
  },
  "filters": {
    "price":{
      "min": 0,
      "max": 54
    }
  }
}


### search services by a user
GET localhost:5000/services/email9@gmail.com/service
Content-Type: application/json

{
  "search_text": "cheese",
  "sort": {
      "by": "price",
      "reverse": true
  },
  "filters": {
    "price":{
      "min": 0,
      "max": 54
    }
  }
}

### POST an user
POST localhost:5000/users
Content-Type: application/json

{
  "email": "pepito@gmail.com",
  "pwd": "12345678",
  "phone": 123456434,
  "name": "Jordi",
  "access": 1
}

### GET concrete service
GET localhost:5000/services/10

### GET service's creator
GET localhost:5000/services/5/user

### GET user's services
GET localhost:5000/services/email2/service

### GET concrete user
GET localhost:5000/users/email1@gmail.com
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2NjcwMTQwMzF9.AeUqg7PaHtNpf9rFBQDsqriDm2CM3PKzaukXbrxigqo loquesea

### POST an LOGIN ---> After this all the following requests needs login(token)
POST localhost:5000/login
Content-Type: application/json

{
  "email": "pepito@gmail.com",
  "pwd": "12345678"
}

### POST an admin LOGIN ---> After this all the following requests needs login(token)
POST localhost:5000/login
Content-Type: application/json

{
  "email": "madmin@gmail.com",
  "pwd": "password"
}

### POST a service
POST http://localhost:5000/services
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2Njk5OTMwMDh9.0YS6kTIH0CyabqP2zskha2PUAb4JPgtsk9rincIydh8 loquesea
Content-Type: application/json

{
  "title": "titleTasdfasdf2",
  "description": "description",
  "price" : 0
}

### PUT a service
PUT localhost:5000/services/10
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzNUBlbWFpbC5jb20iLCJleHAiOjE2NjY5NjU4NDR9.BZWScf1fn4pV3ztRuR6aXy3yQzEr4OvGtWqy-jh8LUM loquesea
Content-Type: application/json

{
  "title": "titulo7",
  "price": 600
}

### GET all reviews
GET localhost:5000/reviews

### POST a review
POST localhost:5000/reviews/1
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2Njk5ODcxMTJ9.1HYKZsMGKcjFAyfxO_HYL0LG5B1xBAscSyE7v8zJmwc loquesea
Content-Type: application/json

{
  "title": "mi primera review",
  "text": "ni mal ni bien",
  "stars": 3
}

### DELETE concrete services
GET localhost:5000/services/1

### DELETE concrete user
DELETE localhost:5000/users/us2@email.com
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzNUBlbWFpbC5jb20iLCJleHAiOjE2NjY5Njc3MzJ9.MmEjGuHsvFUkpiHtnrlJawt7M6S-GHz376kvIeZVOFs loquesea

### PUT update privileges of a user
PUT localhost:5000/users/email1@gmail.com/privileges/7
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzNUBlbWFpbC5jb20iLCJleHAiOjE2NjY5Njc3MzJ9.MmEjGuHsvFUkpiHtnrlJawt7M6S-GHz376kvIeZVOFs loquesea

### POST a contract
POST http://localhost:5000/contracted_services
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hZG1pbkBnbWFpbC5jb20iLCJleHAiOjE2Njk4MjUzODN9.d8j23UC2cHRtbQj60_f3Qh_7Xl1iXPZuqDQhYgaogOA loquesea
Content-Type: application/json

{
  "service": 1,
  "state": "active",
  "price" : 0
}
