### GET all users
GET localhost:5000/users

### GET all services
GET localhost:5000/services

### POST an user
POST localhost:5000/users
Content-Type: application/json

{
  "email": "us5@email.com",
  "pwd": "123456",
  "phone": 123456434,
  "name": "Jordi",
  "acces": 1
}

### GET concrete service
GET localhost:5000/services/10

### GET service's creator
GET localhost:5000/services/5/user

### GET user's services
GET localhost:5000/services/email2/service

### GET concrete user
GET localhost:5000/users/email1223

### POST an LOGIN ---> After this all the following requests needs login(token)
POST localhost:5000/login
Content-Type: application/json

{
  "email": "us5@email.com",
  "pwd": "123456"
}

### POST a service
POST http://localhost:5000/services
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzMkBlbWFpbC5jb20iLCJleHAiOjE2NjY5NjA4ODh9.l2wcdYrRfKzmgrxHvE4bjYgnQUHeCW8VkHcpV0b56_o loquesea
Content-Type: application/json

{
  "title": "titulo6",
  "description": "descripcion",
  "price" : 0
}

### PUT a service
PUT localhost:5000/services/10
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzNUBlbWFpbC5jb20iLCJleHAiOjE2NjY5NjU4NDR9.BZWScf1fn4pV3ztRuR6aXy3yQzEr4OvGtWqy-jh8LUM loquesea
Content-Type: application/json

{
  "title": "titulo7",
  "price": 600
}

### DELETE concrete services
DELETE localhost:5000/services/4

### DELETE concrete user
DELETE localhost:5000/users/us2@email.com
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzNUBlbWFpbC5jb20iLCJleHAiOjE2NjY5Njc3MzJ9.MmEjGuHsvFUkpiHtnrlJawt7M6S-GHz376kvIeZVOFs loquesea



